name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Update composer
        run: composer --verbose self-update --${{ matrix.composer-version }}

      - name: Dump composer verson
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        run: composer --verbose install

      - name: Run tests
        run: |
            cp vendor/sensiolabs/security-advisories/validator.php sa_yaml/8/
            sed -i "s/__DIR__.'/__DIR__.'\/..\/../g" sa_yaml/8/validator.php
            cp vendor/sensiolabs/security-advisories/validator.php sa_yaml/7/
            sed -i "s/__DIR__.'/__DIR__.'\/..\/../g" sa_yaml/7/validator.php
            patch -p1 < patches/validators-what-provides.patch
            php sa_yaml/8/validator.php
            php sa_yaml/7/validator.php
