name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour
  # By using push as well, we make sure our PRs are updated when the main branch has new commits.
  push: 
    branches: 
     - master

jobs:
  violinist:
    name: Run update checks and create PRs
    container:
      image: ghcr.io/violinist-dev/update-check-runner:8.0-multi-composer-2
      env:
        REPO_TOKEN: ${{ secrets.PAT_UPDATE_JOB }}
        PROJECT_URL: ${{ github.repositoryUrl }}
        LICENCE_KEY: ${{ secrets.VALID_CI_LICENCE }}

    runs-on: ubuntu-latest
    steps:
      - name: Update and PR
        run: |
          php /runner
